yoga/core/views.py
from flask import Blueprint, render_template
#from yoga import login_manager
#from yoga.models import Admin,db

core = Blueprint('core',__name__)


@core.route('/')
def home():
    return render_template('index.html')

@core.route('/contacto')
def contacto():
    return render_template('contact.html')

@core.route('/visitanos')
def visitanos():
    return render_template('visitanos.html')

@core.route('/about')
def about():
    return render_template('about.html')

@core.route('/loquehacemos')
def loquehacemos():
    return render_template('servicios.html')

yoga/users/views.py
from flask import Blueprint,render_template,flash,redirect,url_for,request,session
import stripe
from yoga.users.forms import InscripcionesForm,LoginForm, RegistroForm
from yoga.models import Inscriptos
from yoga import db
from yoga.models import Admin
from flask_login import login_user,logout_user,login_required


public_key = "pk_test_TYooMQauvdEDq54NiTphI7jx"

stripe.api_key = "sk_test_4eC39HqLyjWDarjtT1zdp7dc"


users = Blueprint('users',__name__)



@users.route('/users', methods=['GET','POST'])
def inscripciones():


    form = InscripcionesForm()
    try:
        db.engine.dispose()

        logout_user()
    except:
        db.session.rollback()
    if form.validate_on_submit():
        nombre = form.nombre.data
        apellido = form.apellido.data
        session['email'] = form.email.data
        telefono = form.telefono.data
        user = Inscriptos(nombre,apellido,session['email'],telefono)
        if form.check_email(form.email):
            if form.check_curso(form.email):
                flash('Alumno ya suscripto a la base de datos, desea pagar el curso?', 'info')

                return render_template('desea.html',public_key=public_key)
            else:
                flash('El email ya existe y ha pagado el curso, ingrese uno diferente','danger')

                return render_template('inscripciones.html', form=form)
        db.engine.dispose()

        db.session.add(user)
        db.session.commit()
        men = flash('Alumno inscripto','info')


        return render_template('procesando.html',public_key=public_key,men = men)



    return render_template('inscripciones.html', form = form)

@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():
        db.engine.dispose()
        user = Admin.query.filter_by(email=form.email.data).first()
        if user == None:
            return render_template('login.html', men=flash('Usuario o contrasenia invalidos','danger'),form=form)
        if form.email.data == user.email and user.check_password(form.password.data):
            try:
                db.engine.dispose()
                login_user(user)
                flash('ENTRASTE','info')


            except:
                session.rollback()
                print('hubo una excepcion, y se hizo session.rollback()')
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('.listado')
            return redirect(next)
    return render_template('login.html', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('chau pichu','info')
    return redirect(url_for('core.home'))

@users.route('/register', methods = ['GET','POST'])
@login_required
def register():

    form = RegistroForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        db.engine.dispose()
        if form.check_email(form.email):
            flash('El email ya existe')
            return render_template('registrar.html',form = form)
        db.engine.dispose()

        user = Admin(email, password)

        db.session.add(user)

        db.session.commit()


        flash('Usuario agregado','info')
        return redirect(url_for('core.home'))


    return render_template('registrar.html',form = form)

@users.route('/desea')
def desea_cursar():
    return render_template('desea.html')


@users.route('/gracias', methods=['GET','POST'])
def gracias():

    return render_template('gracias.html')


@users.route('/pagos/<int:pagado>', methods=['POST'])
def pagos_curso(pagado):
    customer = stripe.Customer.create(email=request.form['stripeEmail'],
                                      source=request.form['stripeToken'])
 #   print(f'parece que anda {pagado}')
 #   print(customer.email)
 #   for cus in customer:
 #       print(cus)
    charge = stripe.Charge.create(
        customer=customer.id,
        amount=100,
        currency='usd',
        description='Master Yogui diplomatura'
    )
    db.engine.dispose()

    confirmado = Inscriptos.query.filter_by(email=session['email']).first()
    #print(current_user)
    print(confirmado.email)
    for k,v in customer.items():
        print(k,v)

    confirmado.curso_pagado = pagado
    db.engine.dispose()

    db.session.add(confirmado)
    db.session.commit()

    #aviso_inscripcion = EnviarEmail(session['email'])
    #aviso_inscripcion.send()
    logout_user()

    return render_template('gracias.html',pagado=pagado,)
    #return redirect(url_for('users.gracias'))

@users.route('/listado')
@login_required
def listado():
    db.engine.dispose()

    listado = Inscriptos.query.all()
    return render_template('listado.html',listado=listado)

yoga/templates/about.html
{% extends 'base.html' %}

{% block content %}
  <title>{% block title %}Historia | Hacuna{% endblock %}</title>

    <section class="page-section about-heading">
      <script>
AOS.init({
  duration: 1200,
})</script>


<div class="item" data-aos="fade-right">


      <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/about.jpg" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Tradición del yoga</span>
                  <span class="section-heading-lower">Nuestra historia</span>
                </h2>
                <p>Prueba prueba prueba prueba </p>
                <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>

    </section>
{% endblock %}

yoga/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>ADMINISTRADOR</h1>
</body>
</html>

yoga/templates/base.html
<!DOCTYPE html>
<html lang="es">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Hacuna's Yoga {% block title %} {% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Fuentes -->
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Estilos -->
    <link href="{{ url_for('static', filename='css/business-casual.css') }}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
      <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>


  </head>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, men in messages %}

        <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
          <button type="button" class="fade close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

            {{ men }}
        </div>
        {% endfor %}
    {% endif %}
  {% endwith %}
  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">El verdadero Hacuna</span>
      <span class="site-heading-lower">YOGA</span>
    </h1>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{{ url_for('core.home') }}">Hacuna yogi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
             {% if current_user.is_authenticated %}
              <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
              <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('users.listado') }}">Listado de inscriptos</a>
            </li>
                <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('users.register') }}">Registro</a>
             </li>
              {% else %}

            <li class="nav-item active px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('core.home') }}">Inicio</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('core.about') }}">Historia</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('core.visitanos') }}">Visítanos</a>
            </li>
              <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('core.loquehacemos') }}">Lo que hacemos</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('core.contacto') }}">Contacto</a>
            </li>
             <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{{ url_for('users.inscripciones') }}">Incripciones</a>
              </li>
              <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{{ url_for('users.login') }}">Login</a>
              </li>

               {% endif %}
          </ul>

        </div>

      </div>
    </nav>
{% block content %}
    {% endblock %}
    <!-- Pié de página -->
    <footer class="footer text-faded text-center py-5">

      <div class="container">
        <div class="zoom">
        <p class="m-0" >
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
            <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
            <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        </div>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Hacuna Yoga master grand super sayayin capo de todos 2019</p>

      </div>
	</footer>

    <!-- Bootstrap -->
     </body>

</html>

yoga/templates/contact.html
{% extends 'base.html' %}
{% block content %}
    <title>{% block title %}Contacto | Hacuna{% endblock %}</title>

    <section class="page-section about-heading">

   <script>
AOS.init({
  duration: 1200,
})</script>


<div class="item" data-aos="fade-up">


      <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/contact.png" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Envíanos tus dudas</span>
                  <span class="section-heading-lower">Contacto</span>
                </h2>
                <div class="item" data-aos="zoom-out">
                <!-- Formulario de contacto -->
                <form>
                    <div class="form-group">
                        <label>Nombre *</label>
                        <div class="input-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Email *</label>
                        <div class="input-group">
                            <input type="text" class="form-control">
                        </div>
                        <ul class="errorlist">
                            <li>El email no es correcto.</li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <label>Mensaje *</label>
                        <div class="input-group">
                            <textarea class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
                    </div>
                </form>


                <!-- Fin formulario de contacto -->

              </div>

            </div>
          </div>
        </div>
      </div>
     </div>
    </div>

    </section>
{% endblock %}

yoga/templates/desea.html
{% extends 'base.html' %}

{% block content %}
  <title>{% block title %}GRACIAS POR TU COMPRA | Hacuna{% endblock %}</title>
    <section class="page-section about-heading">
      <div class="container">

        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">QUERES COMPRAR?</span>
                  <span class="section-heading-lower">En breve nos comunicaremos con vos</span>

                </h2>
                  <form action="{{ url_for('users.pagos_curso', pagado=1) }}" method="POST">
                    <script src="https://checkout.stripe.com/checkout.js"
                            data-image="static/intro.png"
                            class="stripe-button"
                            data-key={{public_key}}
                            data-amount="100"
                            data-name="Diplomatura master"
                            data-description = "Curso"
                            data-locale="auto"
                            data-zip-code="true">
                    </script>
                       <button id="botoncito" class="btn btn-xl btn-primary w-250" type="submit">Pagar curso<strike>$4000</strike><span class="pl-4">$3500</span></button><br>

                    <script>botoncito.click();</script>

                  </form>


                <p>Nos vamos cada tanto a Bs As a capacitarnos </p>
                <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

yoga/templates/gracias.html
{% extends 'base.html' %}

{% block content %}
  <title>{% block title %}GRACIAS POR TU COMPRA | Hacuna{% endblock %}</title>

    <section class="page-section about-heading">

         <script>
AOS.init({
  duration: 1200,
})</script>


<div class="item" data-aos="zoom-in">
      <div class="container">

        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                    {% if pagado == 1 %}
                  <span class="section-heading-upper">Gracias por inscribirte y pagar el curso</span>
                  <span class="section-heading-lower">En breve nos comunicaremos con vos</span>
                    {% else %}
                    <span class="section-heading-upper">Gracias</span>
                  <span class="section-heading-lower">no me vas a poder hackear</span>
                    {% endif %}
                </h2>



                <div class="item" data-aos="slide-up">
                <p>Nos vamos cada tanto a Bs As a capacitarnos noma </p>
                <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
     </div>
    </div>
    </section>
{% endblock %}

yoga/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <title>{% block title %}Inicio | Home{% endblock %}</title>
   <script>
AOS.init({
  duration: 1200,
})</script>


    <!-- Cabecera -->
    <section class="page-section clearfix">
     <div class="item" data-aos="flip-up">
      <div class="container">
        <div class="intro">
          <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="static/intro.png" alt="">
          <div class="intro-text left-0 text-center bg-faded p-5 rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Relajate</span>
              <span class="section-heading-lower">Te gustará</span>
            </h2>
            <p class="mb-3">Somos expertos, enserio.
            </p>
            <div class="intro-button mx-auto">
            <div class="item" data-aos="flip-down">
              <a class="btn btn-primary btn-xl" href="{{ url_for('core.visitanos') }}">Visítanos</a>
            </div>
          </div>
        </div>
      </div>
     </div>
     </div>
    </section>

    <!-- Mensaje -->
    <section class="page-section cta">
     <div class="item" data-aos="flip-left">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
            </div>
          </div>
        </div>
      </div>
     </div>
    </section>

<div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-6">
          <div class="item" data-aos="flip-right">

      <div class="card text-center bg-light border-4" style= "margin: .25rem">
        <div class="card-block">
        <img src="static/avala.png" class="card-img-top rounded-circle" alt="...">
        <div class="card-body cards ">
          <h5 class="card-title text-uppercase text-black">YOGA-FIRE</h5>
          <p class="card-text text-black">Dalsim <br> Se compone de frijoles, arroz con pimientos rojos finamente cortados en cubitos y cebollas, plátanos fritos, una ensalada de repollo con tomate y zanahoria, y una selección de carne entre pollo, pescado, carne de cerdo o de ternera con cebollas asadas.</p>
          <p style="display: none;" >La carne que viene con un casado a la parrilla o salteados, pero nunca frito. A veces, el casado incluye papas fritas o verduras adicionales, tales como los aguacates.</p>
          <a href="#"  class="btn btn-warning">Leer Mas...</a>
        </div>
       </div>
       </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6">
          <div class="item" data-aos="fade-left">

      <div class="card text-center bg-light border-4" style= "margin: .5rem">
        <div class="card-block">
        <img src="static/avala2.png" class="card-img-top rounded-circle" alt="...">
        <div class="card-body cards ">
          <h5 class="card-title text-uppercase text-black">HORIUKEN</h5>
          <p class="card-text text-black">Casado o comida típica, es el plato más común en Costa Rica. <br> Se compone de frijoles, arroz con pimientos rojos finamente cortados en cubitos y cebollas, plátanos fritos, una ensalada de repollo con tomate y zanahoria, y una selección de carne entre pollo, pescado, carne de cerdo o de ternera con cebollas asadas.</p>
          <p style="display: none;" >La carne que viene con un casado a la parrilla o salteados, pero nunca frito. A veces, el casado incluye papas fritas o verduras adicionales, tales como los aguacates.</p>
          <a href="#" class="btn btn-warning">Leer Mas...</a>
        </div>
       </div>
      </div>
    </div>
    </div>

    <div class="col-md-3 col-sm-6">
         <div class="item" data-aos="fade-right">

      <div class="card text-center bg-light border-4" style= "margin: 1rem">
        <div class="card-block">
        <img src="static/products-01.png" class="card-img-top rounded-circle" alt="...">
        <div class="card-body cards ">
          <h5 class="card-title text-uppercase text-black">ADUKEN</h5>
          <p class="card-text text-black">Casado o comida típica, es el plato más común en Costa Rica. <br> Se compone de frijoles, arroz con pimientos rojos finamente cortados en cubitos y cebollas, plátanos fritos, una ensalada de repollo con tomate y zanahoria, y una selección de carne entre pollo, pescado, carne de cerdo o de ternera con cebollas asadas.</p>
          <p style="display: none;" >La carne que viene con un casado a la parrilla o salteados, pero nunca frito. A veces, el casado incluye papas fritas o verduras adicionales, tales como los aguacates.</p>
          <a href="#" class="btn btn-warning">Leer Mas...</a>
        </div>
       </div>
      </div>
    </div>
    </div>

    <div class="col-md-3 col-sm-6">
          <div class="item" data-aos="fade-down">

      <div class="card text-center bg-light border-4" style= "margin: 1.5rem">
        <div class="card-block">
        <img src="static/products-03.png" class="card-img-top rounded-circle" alt="...">
        <div class="card-body cards ">
          <h5 class="card-title text-uppercase text-black">KONTANTEBRUKEN</h5>
          <p class="card-text text-black">Casado o comida típica, es el plato más común en Costa Rica. <br> Se compone de frijoles, arroz con pimientos rojos finamente cortados en cubitos y cebollas, plátanos fritos, una ensalada de repollo con tomate y zanahoria, y una selección de carne entre pollo, pescado, carne de cerdo o de ternera con cebollas asadas.</p>
          <p style="display: none;" >La carne que viene con un casado a la parrilla o salteados, pero nunca frito. A veces, el casado incluye papas fritas o verduras adicionales, tales como los aguacates.</p>
          <a href="#"  class="btn btn-warning">Leer Mas...</a>
        </div>
       </div>
      </div>
    </div>
   </div>
  </div>
</div>


{% endblock %}

yoga/templates/inscripciones.html
{% extends 'base.html' %}
{% block content %}

   <script>
AOS.init({
  duration: 1200,
})</script>


    <title>{% block title %}Inscripciones | Hacuna {% endblock %}</title>
<section class="page-section about-heading">
      <div class="container">
      <div class="item" data-aos="flip-down">

        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/contact.png" alt="">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/intro.png" alt="">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/avala.png" alt="">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="static/avala2.png" alt="">
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Inscribite a nuestros cursos</span>
                  <span class="section-heading-lower">Paga con tarjeta de credito</span>
                </h2>

                <!-- Formulario de contacto -->
                <form  method="POST">

                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label>{{ form.nombre.label(class='form-group') }}</label>
                        <div class="input-group">
                            {{ form.nombre(class='input-group') }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label>{{ form.apellido.label(class='form-group') }}</label>
                        <div class="input-group">
                            {{ form.apellido(class='input-group') }}
                        </div>
                    </div>
                    <div class="form-group">

                        <label>{{ form.email.label(class='form-group') }}</label>
                        <div class="input-group">
                            {{ form.email(class='input-group') }}
                             {% if form.email.errors %}
                            <script>alert('El e-mail es incorrecto')</script>


                            {% endif %}
                        </div>

                    </div>
                     <div class="form-group">
                        <label>{{ form.telefono.label(class='form-group') }}</label>
                        <div class="input-group">
                            {{ form.telefono(class='input-group') }}
                                  {% if form.telefono.errors %}
                            <script>alert('El telefono es incorrecto')</script>
                            {% endif %}
                        </div>
                    </div>
                    <div class="text-center">
                        {{ form.submit(class="btn btn-primary btn-block py-2") }}

                    </div>

                </form>


                <!-- Fin formulario de contacto -->

              </div>
            </div>
          </div>
        </div>
      </div>
      </div>

    </section>
{% endblock %}

yoga/templates/procesando.html
{% extends 'base.html' %}

{% block content %}
  <title>{% block title %}GRACIAS POR TU COMPRA | Hacuna{% endblock %}</title>
    <section class="page-section about-heading">
      <div class="container">

        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">PROCESANDO tu inscripcion</span>
                  <span class="section-heading-lower">En breve nos comunicaremos con vos</span>

                </h2>


                  <form action="{{ url_for('users.pagos_curso', pagado=1) }}" method="POST">
                    <script src="https://checkout.stripe.com/checkout.js"
                            data-image="static/intro.png"
                            class="stripe-button"
                            data-key={{public_key}}
                            data-amount="100"
                            data-name="Diplomatura master"
                            data-description = "Curso"
                            data-locale="auto"
                            data-zip-code="true"

                    >

                    </script>
                       <button id="botoncito" class="btn btn-xl btn-primary w-250" type="submit">Pagar curso<strike>$4000</strike><span class="pl-4">$3500</span></button><br>
                        <script>botoncito.click();</script>
                  </form>

                  <h2>VERIFICANDO</h2>
                <p>Nos vamos cada tanto a Bs As a capacitarnos</p>
                <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean in efficitur enim.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}